# Generated by Django 5.1.2 on 2024-10-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Accno', models.IntegerField(primary_key='Accno', serialize=False)),
                ('DOB', models.DateField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Mobileno', models.IntegerField()),
                ('Aadharno', models.IntegerField()),
            ],
        ),
    ]
